# name: deploy to wsl 

# pipeline:
#   stages:
#     - test
#     - build
#     - prod

stages:
  - test-front


test-front:
  script:
    - echo 'Запуск тестов активирован'
    - cd frontend
    - npm ci
    - npm run test